apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  # Kustomize local deploy will ignored the resource with this annotation
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
spec: {}
