apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
    name: apps-secret-store
    namespace: apps
spec:
    provider:
        vault:
            server: "http://vault.vault.svc.cluster.local:8200"
            path: "apps"
            version: "v2"
            auth:
                kubernetes:
                    mountPath: "kubernetes"
                    role: "apps-secret-store"
                    serviceAccountRef:
                        name: "apps-secret-store"
