apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    namespace: kube-system
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.9.1
    valuesInline:
      controller:
        service:
          annotations:
            metallb.universe.tf/loadBalancerIPs: 192.168.1.8
