apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

helmCharts:
    - name: vault
      namespace: vault
      releaseName: vault
      repo: https://helm.releases.hashicorp.com
      version: 0.27.0
      valuesFile: values.yaml

resources:
    - namespace.yaml
