apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

helmCharts:
  - name: argo-cd
    namespace: argocd
    releaseName: argo-cd
    version: 6.4.0
    repo: https://argoproj.github.io/argo-helm
    # Override `argocd-server` instead of `argocd-argocd-server`
    valuesInline:
      fullnameOverride: argocd
      global:
        domain: argocd.k8s.local
resources:
  - ingress.yaml
