apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-operator
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://mariadb-operator.github.io/mariadb-operator
      targetRevision: 0.25.0
      helm:
        valuesObject:
          metrics:
            enabled: true
          webhook:
            cert:
              certManager:
                enabled:
                  true
  destination:
    server: https://kubernetes.default.svc
    namespace: mariadb-operator
