apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
    name: homelab-secret
    namespace: apps
spec:
    type: kv-v2

    # mount path
    mount: internal

    # path of the secret
    path: homepage

    # dest k8s secret
    destination:
        name: homepage-secret
        create: true
        overwrite: true

    # static secret refresh interval
    refreshAfter: 0s

    # Name of the CRD to authenticate to Vault
    vaultAuthRef: static-auth
