apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
    name: static-auth
    namespace: apps
spec:
    method: kubernetes
    mount: kubernetes
    kubernetes:
        role: homepage
        serviceAccount: homepage
        audiences:
            - vault
