apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: {{  .Values.spec.source.repoURL  }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{  .Values.spec.destination.server }}
    namespace: cert-manager
