apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: self-signed-cluster-issuer
spec:
    selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: self-signed-ca
spec:
    isCA: true
    commonName: k8s.local
    secretName: root-secret
    privateKey:
        algorithm: ECDSA
        size: 256
    issuerRef:
        name: self-signed-cluster-issuer
        kind: ClusterIssuer
        group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: self-signed-ca-issuer
spec:
    ca:
        secretName: root-secret
