# kustomize build . --enable-helm | kubectl apply -f -; rm -r ./charts
# kustomize build . --enable-helm | kubectl delete -f -; rm -r ./charts
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    namespace: kube-system
    repo: https://charts.jetstack.io
    version: v1.14.3
    valuesInline:
      installCRDs: false

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.crds.yaml
  - clusterissuer.yaml
