apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding.yaml
- clusterrole.yaml
- configmap.yaml
- deployment.yaml
- ingress.yaml
- secret.yaml
- serviceaccount.yaml
- service.yaml
