apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

helmCharts:
  - name: metallb
    namespace: metallb-system
    releaseName: metallb
    repo: https://metallb.github.io/metallb
    # when using cilium with IPAM cluster-pool, set metallb with loadBalancerClass name
    # https://metallb.universe.tf/installation/#setting-the-loadbalancer-class
    # valuesInline:
    #   loadBalancerClass: metallb
    version: 0.14.3

resources:
  - IPAddressPool.yaml
  - l2advertisement.yaml
  - namespace.yaml
