apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

helmCharts:
    - name: secrets-store-csi-driver
      namespace: kube-system
      releaseName: secrets-store-csi-driver
      repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.4.1
      valuesInline:
          syncSecret.enabled: true
          enableSecretRotation: true

resources:
  - secretproviderclass.yaml
