apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: internal-vault-provider
    namespace: apps
spec:
    provider: vault # accepted provider options: akeyless or azure or vault or gcp
    parameters: # provider-specific parameters
        roleName: homepage
        vaultAddress: http://vault.vault.svc.cluster.local:8200
        objects: |
            - secretPath: "apps/homepage"
              objectName: "HOMEPAGE_VAR_PROXMOX_PASSWORD"
              secretKey: "HOMEPAGE_VAR_PROXMOX_PASSWORD"
            - secretPath: "apps/homepage"
              objectName: "HOMEPAGE_VAR_PROXMOX_USERNAME"
              secretKey: "HOMEPAGE_VAR_PROXMOX_USERNAME"
