apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: homepage-secret
spec:
    refreshInterval: "15s"
    secretStoreRef:
        name: apps-secret-store
        kind: SecretStore
    target:
        name: homepage-secret
    dataFrom:
        - extract:
              key: homepage
