# Direct deploy with kubectl apply -k .
# kustomize build . | kubectl apply -f -
# kustomize build base
# kustomize build .
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

patches:
- path: ingress.patch.yaml
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: homepage.k8s.local
  target:
    kind: Ingress
    name: homepage
resources:
- base
